language: python
python:
  - 3.8

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install -U poetry
- pip install -U tox-travis


# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password

before-deploy:
  poetry config pypi-token.pypi $PYPI_TOKEN

deploy:
  provider: script
  script: poetry publish --build
  skip_cleaning: true
  on:
    repo: sugix/SelectStar_SV_Solution
    python: 3.8
